export const modelMockData = {
    'createBuffer': {
        desp: null,
        group: "矢量大数据",
        id: "12",
        method: "POST",
        name: "创建缓冲分析任务",
        modelType: "bigdata",
        params: [
            {
                "index": 1,
                "name": "srcLayer.srcUrl",
                "briefDescp": "输入图层URL",
                "descp": "原始输入图层URL地址",
                "dataType": "GEOMETRY",
                "dataSourceType": "PG",
                "dataTypeExt": "gisData",
                "defauleValue": null,
                "direction": "IN.URL",
                "example": "hdfs://192.168.96.101:9000/mapgisanalystserver/nyc/trip_data_1.csv",
                "need": true,
                "xattrs": null
            },
            {
                "index": 2,
                "name": "srcLayer.schema",
                "briefDescp": "输入图层元信息URL",
                "descp": "输入原始图层元信息json的URL地址，支持hdfs、http",
                "dataType": "STRING",
                "dataSourceType": null,
                "dataTypeExt": "common",
                "defauleValue": null,
                "direction": null,
                "example": "hdfs://192.168.96.101:9000/mapgisanalystserver/datasetschema.json",
                "need": false,
                "xattrs": null
            },
            {
                "index": 3,
                "name": "srcLayer.filter",
                "briefDescp": "输入图层过滤条件",
                "descp": "输入原始图层属性过滤条件",
                "dataType": "STRING",
                "dataSourceType": null,
                "dataTypeExt": "common",
                "defauleValue": null,
                "direction": null,
                "example": "speed>100 and id>0",
                "need": false,
                "xattrs": null
            },
            {
                "index": 22,
                "name": "extend.xmin",
                "briefDescp": "空间范围xmin",
                "descp": "空间范围信息，x轴最小值",
                "dataType": "DOUBLE",
                "dataSourceType": null,
                "dataTypeExt": "common",
                "defauleValue": null,
                "direction": null,
                "example": "-74.25559136",
                "need": false,
                "xattrs": null
            },
            {
                "index": 23,
                "name": "extend.xmax",
                "briefDescp": "空间范围xmax",
                "descp": "空间范围信息，x轴最大值",
                "dataType": "DOUBLE",
                "dataSourceType": null,
                "dataTypeExt": "common",
                "defauleValue": null,
                "direction": null,
                "example": "-73.70000906",
                "need": false,
                "xattrs": null
            },
            {
                "index": 24,
                "name": "extend.ymin",
                "briefDescp": "空间范围ymin",
                "descp": "空间范围信息，y轴最小值",
                "dataType": "DOUBLE",
                "dataSourceType": null,
                "dataTypeExt": "common",
                "defauleValue": null,
                "direction": null,
                "example": "40.4961154",
                "need": false,
                "xattrs": null
            },
            {
                "index": 25,
                "name": "extend.ymax",
                "briefDescp": "空间范围ymax",
                "descp": "空间范围信息，y轴最大值",
                "dataType": "DOUBLE",
                "dataSourceType": null,
                "dataTypeExt": "common",
                "defauleValue": null,
                "direction": null,
                "example": "40.91553278",
                "need": false,
                "xattrs": null
            },
            {
                "index": 26,
                "name": "extend.startTime",
                "briefDescp": "时间范围start",
                "descp": "时间范围信息，起始时间",
                "dataType": "LONG",
                "dataSourceType": null,
                "dataTypeExt": "common",
                "defauleValue": null,
                "direction": null,
                "example": "",
                "need": false,
                "xattrs": null
            },
            {
                "index": 27,
                "name": "extend.endTime",
                "briefDescp": "时间范围end",
                "descp": "时间范围信息，结束时间",
                "dataType": "LONG",
                "dataSourceType": null,
                "dataTypeExt": "common",
                "defauleValue": null,
                "direction": null,
                "example": "",
                "need": false,
                "xattrs": null
            },
            {
                "index": 31,
                "name": "bufferMethod",
                "briefDescp": "缓冲方式",
                "descp": "缓冲计算的方式，distance：通过指定距离进行缓冲；expression：通过表达式计算进行缓冲；",
                "dataType": "ENUM",
                "dataSourceType": null,
                "dataTypeExt": "common",
                "defauleValue": "distance,expression",
                "direction": null,
                "example": "distance",
                "need": true,
                "xattrs": null
            },
            {
                "index": 32,
                "name": "distanceOrExp",
                "briefDescp": "距离或表达式",
                "descp": "缓冲距离或者表达式的值，当为指定距离时，可指定距离单位",
                "dataType": "STRING",
                "dataSourceType": null,
                "dataTypeExt": "common",
                "defauleValue": "",
                "direction": null,
                "example": "fld*12+1 或 0.001",
                "need": true,
                "xattrs": null
            },
            {
                "index": 33,
                "name": "spatialUnit",
                "briefDescp": "缓冲距离单位",
                "descp": "缓冲距离单位，meter(米)、kilometer(千米)、none(数据单位)",
                "dataType": "ENUM",
                "dataSourceType": null,
                "dataTypeExt": "common",
                "defauleValue": "meter,kilometer,none",
                "direction": null,
                "example": "",
                "need": true,
                "xattrs": null
            },
            {
                "index": 35,
                "name": "bufferType",
                "briefDescp": "缓冲类型",
                "descp": "缓冲类型，flat(平头)、round(圆头)",
                "dataType": "ENUM",
                "dataSourceType": null,
                "dataTypeExt": "common",
                "defauleValue": "flat,round",
                "direction": null,
                "example": "round",
                "need": true,
                "xattrs": null
            },
            {
                "index": 42,
                "name": "option",
                "briefDescp": "缓冲选项",
                "descp": "缓冲选项，all(聚合所有)、list(聚合相交部分)、none(不做处理)",
                "dataType": "ENUM",
                "dataSourceType": null,
                "dataTypeExt": "common",
                "defauleValue": "all,list,none",
                "direction": null,
                "example": "",
                "need": true,
                "xattrs": null
            },
            {
                "index": 43,
                "name": "reserveFields",
                "briefDescp": "保留字段数组",
                "descp": "保留字段数组，用逗号分隔",
                "dataType": "STRING",
                "dataSourceType": null,
                "dataTypeExt": "common",
                "defauleValue": null,
                "direction": null,
                "example": "fld1,fld2,fld3.fld4",
                "need": false,
                "xattrs": null
            },
            {
                "index": 44,
                "name": "isMultipart",
                "briefDescp": "是否合并为多部分",
                "descp": "几何是否合并为多部分,当保留字段选项all、list时生效",
                "dataType": "BOOLEAN",
                "dataSourceType": null,
                "dataTypeExt": "common",
                "defauleValue": null,
                "direction": null,
                "example": "false",
                "need": false,
                "xattrs": null
            },
            {
                "index": 52,
                "name": "statisticFields",
                "briefDescp": "统计字段信息",
                "descp": "统计字段信息，当保留字段选项all、list时生效，值型字段支持 count,min,max,mean,sum,variance,stddev,range 等",
                "dataType": "STRING",
                "dataSourceType": null,
                "dataTypeExt": "common",
                "defauleValue": null,
                "direction": null,
                "example": "[{\"field\":\"trip_distance\",\"statisticTypes\":[\"mean\",\"sum\"]},{\"field\":\"speed\",\"statisticTypes\":[\"mean\", \"count\"]}]",
                "need": false,
                "xattrs": null
            },
            {
                "index": 62,
                "name": "rtnUrl",
                "briefDescp": "结果图层URL",
                "descp": "结果图层地址，具有一定规则的数据地址，即{协议}://{用户名}@{密码}/{IP}:{port}/{路径}",
                "dataType": "GEOMETRY",
                "dataSourceType": "PG",
                "dataTypeExt": "gisData",
                "defauleValue": null,
                "direction": "OUT.URL",
                "example": "pg://mapgis@mapgis/192.168.81.223:5432/postgis/summarymesh_hexgon_96_101_001 或者 hdfs://192.168.96.101:9000/nyc",
                "need": true,
                "xattrs": null
            },
            {
                "index": 63,
                "name": "rtnUrlUserName",
                "briefDescp": "结果图层数据库用户",
                "descp": "输出图层数据库时使用的用户名，默认为DataStore中访问数据库的用户名",
                "dataType": "STRING",
                "dataSourceType": null,
                "dataTypeExt": "common",
                "defauleValue": null,
                "direction": null,
                "example": "admin",
                "need": false,
                "xattrs": null
            },
            {
                "index": 64,
                "name": "rtnUrlPasswd",
                "briefDescp": "结果图层数据库密码",
                "descp": "输出图层数据库时使用的密码，默认为DataStore中访问数据库的密码",
                "dataType": "STRING",
                "dataSourceType": null,
                "dataTypeExt": "common",
                "defauleValue": null,
                "direction": null,
                "example": "sa",
                "need": false,
                "xattrs": null
            }
        ],
        url: "/analysticservice/v1.0/job/createBuffer/submit?",
        version: null
    },
    'overlaySummary': {
        "modelType": "bigdata",
        "id": "13",
        "name": "叠加分析任务",
        "version": null,
        "group": "矢量大数据",
        "desp": null,
        "url": "/analysticservice/v1.0/job/overlaySummary/submit?",
        "method": "POST",
        "params": [
            {
                "index": 1,
                "name": "srcLayer.srcUrl",
                "briefDescp": "输入图层URL",
                "descp": "原始输入图层URL地址",
                "dataType": "GEOMETRY",
                "dataSourceType": "PG",
                "dataTypeExt": "gisData",
                "defauleValue": null,
                "direction": "IN.URL",
                "example": "hdfs://192.168.96.101:9000/mapgisanalystserver/nyc/trip_data_1.csv",
                "need": true,
                "xattrs": null
            },
            {
                "index": 2,
                "name": "srcLayer.schema",
                "briefDescp": "输入图层元信息URL",
                "descp": "输入原始图层元信息json的URL地址，支持hdfs、http",
                "dataType": "STRING",
                "dataSourceType": null,
                "dataTypeExt": "common",
                "defauleValue": null,
                "direction": null,
                "example": "hdfs://192.168.96.101:9000/mapgisanalystserver/datasetschema.json",
                "need": false,
                "xattrs": null
            },
            {
                "index": 3,
                "name": "srcLayer.filter",
                "briefDescp": "输入图层过滤条件",
                "descp": "输入原始图层属性过滤条件",
                "dataType": "STRING",
                "dataSourceType": null,
                "dataTypeExt": "common",
                "defauleValue": null,
                "direction": null,
                "example": "speed>100 and id>0",
                "need": false,
                "xattrs": null
            },
            {
                "index": 22,
                "name": "extend.xmin",
                "briefDescp": "空间范围xmin",
                "descp": "空间范围信息，x轴最小值",
                "dataType": "DOUBLE",
                "dataSourceType": null,
                "dataTypeExt": "common",
                "defauleValue": null,
                "direction": null,
                "example": "-74.25559136",
                "need": false,
                "xattrs": null
            },
            {
                "index": 23,
                "name": "extend.xmax",
                "briefDescp": "空间范围xmax",
                "descp": "空间范围信息，x轴最大值",
                "dataType": "DOUBLE",
                "dataSourceType": null,
                "dataTypeExt": "common",
                "defauleValue": null,
                "direction": null,
                "example": "-73.70000906",
                "need": false,
                "xattrs": null
            },
            {
                "index": 24,
                "name": "extend.ymin",
                "briefDescp": "空间范围ymin",
                "descp": "空间范围信息，y轴最小值",
                "dataType": "DOUBLE",
                "dataSourceType": null,
                "dataTypeExt": "common",
                "defauleValue": null,
                "direction": null,
                "example": "40.4961154",
                "need": false,
                "xattrs": null
            },
            {
                "index": 25,
                "name": "extend.ymax",
                "briefDescp": "空间范围ymax",
                "descp": "空间范围信息，y轴最大值",
                "dataType": "DOUBLE",
                "dataSourceType": null,
                "dataTypeExt": "common",
                "defauleValue": null,
                "direction": null,
                "example": "40.91553278",
                "need": false,
                "xattrs": null
            },
            {
                "index": 26,
                "name": "extend.startTime",
                "briefDescp": "时间范围start",
                "descp": "时间范围信息，起始时间",
                "dataType": "LONG",
                "dataSourceType": null,
                "dataTypeExt": "common",
                "defauleValue": null,
                "direction": null,
                "example": "",
                "need": false,
                "xattrs": null
            },
            {
                "index": 27,
                "name": "extend.endTime",
                "briefDescp": "时间范围end",
                "descp": "时间范围信息，结束时间",
                "dataType": "LONG",
                "dataSourceType": null,
                "dataTypeExt": "common",
                "defauleValue": null,
                "direction": null,
                "example": "",
                "need": false,
                "xattrs": null
            },
            {
                "index": 32,
                "name": "overlayLayer.srcUrl",
                "briefDescp": "叠加图层URL",
                "descp": "叠加图层URL地址",
                "dataType": "GEOMETRY",
                "dataSourceType": "PG",
                "dataTypeExt": "gisData",
                "defauleValue": null,
                "direction": "IN.URL",
                "example": "hdfs://192.168.96.101:9000/mapgisanalystserver/nyc/trip_data_1.csv",
                "need": true,
                "xattrs": null
            },
            {
                "index": 33,
                "name": "overlayLayer.schema",
                "briefDescp": "叠加图层元信息URL",
                "descp": "叠加图层元信息",
                "dataType": "STRING",
                "dataSourceType": null,
                "dataTypeExt": "common",
                "defauleValue": null,
                "direction": null,
                "example": "hdfs://192.168.96.101:9000/mapgisanalystserver/datasetschema.json",
                "need": false,
                "xattrs": null
            },
            {
                "index": 34,
                "name": "overlayLayer.filter",
                "briefDescp": "叠加图层过滤条件",
                "descp": "叠加图层属性过滤条件",
                "dataType": "STRING",
                "dataSourceType": null,
                "dataTypeExt": "common",
                "defauleValue": null,
                "direction": null,
                "example": "speed>100",
                "need": false,
                "xattrs": null
            },
            {
                "index": 35,
                "name": "overlayalgorithm",
                "briefDescp": "叠加算法",
                "descp": "叠加分析算法选择，支持mapgis和jts算法",
                "dataType": "ENUM",
                "dataSourceType": null,
                "dataTypeExt": "common",
                "defauleValue": "mapgis,jts",
                "direction": null,
                "example": null,
                "need": true,
                "xattrs": null
            },
            {
                "index": 36,
                "name": "srckeepfields",
                "briefDescp": "源图层保留字段",
                "descp": "源图层保留字段",
                "dataType": "STRING",
                "dataSourceType": null,
                "dataTypeExt": "common",
                "defauleValue": null,
                "direction": null,
                "example": null,
                "need": false,
                "xattrs": null
            },
            {
                "index": 37,
                "name": "layerkeepfields",
                "briefDescp": "叠加图层保留字段",
                "descp": "叠加图层保留字段",
                "dataType": "STRING",
                "dataSourceType": null,
                "dataTypeExt": "common",
                "defauleValue": null,
                "direction": null,
                "example": null,
                "need": false,
                "xattrs": null
            },
            {
                "index": 40,
                "name": "partitionnum",
                "briefDescp": "分区数",
                "descp": "分区数控制叠加任务并行度",
                "dataType": "INT",
                "dataSourceType": null,
                "dataTypeExt": "common",
                "defauleValue": null,
                "direction": null,
                "example": null,
                "need": true,
                "xattrs": null
            },
            {
                "index": 41,
                "name": "rongcha",
                "briefDescp": "容差",
                "descp": "容差",
                "dataType": "DOUBLE",
                "dataSourceType": null,
                "dataTypeExt": "common",
                "defauleValue": null,
                "direction": null,
                "example": null,
                "need": true,
                "xattrs": null
            },
            {
                "index": 42,
                "name": "overlayType",
                "briefDescp": "叠加类型",
                "descp": "叠加类型，给值： eraser,interset,symdifference, union",
                "dataType": "ENUM",
                "dataSourceType": null,
                "dataTypeExt": "common",
                "defauleValue": "相减,相交,求并,判别,对称差",
                "direction": null,
                "example": "",
                "need": true,
                "xattrs": null
            },
            {
                "index": 43,
                "name": "statisticFields",
                "briefDescp": "统计字段信息",
                "descp": "统计字段信息 ， 数值型字段支持 count,min,max,mean,sum,variance,stddev,range 等",
                "dataType": "STRING",
                "dataSourceType": null,
                "dataTypeExt": "common",
                "defauleValue": null,
                "direction": null,
                "example": "[{\"field\":\"trip_distance\",\"statisticTypes\":[\"mean\",\"sum\"]},{\"field\":\"speed\",\"statisticTypes\":[\"mean\", \"count\"]}]",
                "need": false,
                "xattrs": null
            },
            {
                "index": 44,
                "name": "engineType",
                "briefDescp": "计算引擎",
                "descp": "计算引擎，支持spark,postgis，默认为spark",
                "dataType": "ENUM",
                "dataSourceType": null,
                "dataTypeExt": "common",
                "defauleValue": "spark,pg",
                "direction": null,
                "example": "spark",
                "need": true,
                "xattrs": null
            },
            {
                "index": 52,
                "name": "rtnUrl",
                "briefDescp": "结果图层URL",
                "descp": "结果图层地址，具有一定规则的数据地址，即{协议}://{用户名}@{密码}/{IP}:{port}/{路径}",
                "dataType": "GEOMETRY",
                "dataSourceType": "PG",
                "dataTypeExt": "gisData",
                "defauleValue": null,
                "direction": "OUT.URL",
                "example": "pg://mapgis@mapgis/192.168.81.223:5432/postgis/summarymesh_hexgon_96_101_001 或者 hdfs://192.168.96.101:9000/nyc",
                "need": true,
                "xattrs": null
            },
            {
                "index": 53,
                "name": "writetype",
                "briefDescp": "结果写回方式",
                "descp": "copy:用copy方式写回postgresql数据库；insert:spark批量插入方式写回postgresql",
                "dataType": "ENUM",
                "dataSourceType": null,
                "dataTypeExt": "common",
                "defauleValue": "copy,insert",
                "direction": null,
                "example": null,
                "need": true,
                "xattrs": null
            },
            {
                "index": 54,
                "name": "rtnUrlUserName",
                "briefDescp": "结果图层数据库用户",
                "descp": "输出图层数据库时使用的用户名，默认为DataStore中访问数据库的用户名",
                "dataType": "STRING",
                "dataSourceType": null,
                "dataTypeExt": "common",
                "defauleValue": null,
                "direction": null,
                "example": "admin",
                "need": false,
                "xattrs": null
            },
            {
                "index": 55,
                "name": "rtnUrlPasswd",
                "briefDescp": "结果图层数据库密码",
                "descp": "输出图层数据库时使用的密码，默认为DataStore中访问数据库的密码",
                "dataType": "STRING",
                "dataSourceType": null,
                "dataTypeExt": "common",
                "defauleValue": null,
                "direction": null,
                "example": "sa",
                "need": false,
                "xattrs": null
            }
        ]
    },
    'igsBuffer': {
        "modelType": "igs",
        "id": "600231",
        "name": "类缓冲分析(单圈)",
        "version": "",
        "group": "缓冲分析",
        "desp": null,
        "url": null,
        "method": null,
        "params": [
            {
                "index": 1,
                "name": "srcInfo",
                "briefDescp": null,
                "descp": null,
                "dataType": "STRING",
                "dataSourceType": null,
                "dataTypeExt": "gisData",
                "defauleValue": "GDBP://mapgislocal/Sample/sfcls/overLayA",
                "direction": "IN",
                "example": null,
                "need": null,
                "xattrs": null
            },
            {
                "index": 2,
                "name": "desInfo",
                "briefDescp": null,
                "descp": null,
                "dataType": "STRING",
                "dataSourceType": null,
                "dataTypeExt": "gisData",
                "defauleValue": "GDBP://mapgislocal/Sample/sfcls/bufferSigle1",
                "direction": "OUT",
                "example": null,
                "need": null,
                "xattrs": null
            },
            {
                "index": 3,
                "name": "idstr",
                "briefDescp": null,
                "descp": null,
                "dataType": "STRING",
                "dataSourceType": null,
                "dataTypeExt": "common",
                "defauleValue": "",
                "direction": "IN",
                "example": null,
                "need": null,
                "xattrs": null
            },
            {
                "index": 4,
                "name": "leftRad",
                "briefDescp": null,
                "descp": null,
                "dataType": "FLOAT",
                "dataSourceType": null,
                "dataTypeExt": "common",
                "defauleValue": "5",
                "direction": "IN",
                "example": null,
                "need": null,
                "xattrs": null
            },
            {
                "index": 5,
                "name": "rightRad",
                "briefDescp": null,
                "descp": null,
                "dataType": "FLOAT",
                "dataSourceType": null,
                "dataTypeExt": "common",
                "defauleValue": "5",
                "direction": "IN",
                "example": null,
                "need": null,
                "xattrs": null
            },
            {
                "index": 6,
                "name": "isByAtt",
                "briefDescp": null,
                "descp": null,
                "dataType": "BOOLEAN",
                "dataSourceType": null,
                "dataTypeExt": "common",
                "defauleValue": "false",
                "direction": "IN",
                "example": null,
                "need": null,
                "xattrs": null
            },
            {
                "index": 7,
                "name": "fldName",
                "briefDescp": null,
                "descp": null,
                "dataType": "STRING",
                "dataSourceType": null,
                "dataTypeExt": "common",
                "defauleValue": "",
                "direction": "IN",
                "example": null,
                "need": null,
                "xattrs": null
            },
            {
                "index": 8,
                "name": "angleType",
                "briefDescp": null,
                "descp": null,
                "dataType": "INT",
                "dataSourceType": null,
                "dataTypeExt": "common",
                "defauleValue": "0",
                "direction": "IN",
                "example": null,
                "need": null,
                "xattrs": null
            },
            {
                "index": 9,
                "name": "isDynPrj",
                "briefDescp": null,
                "descp": null,
                "dataType": "BOOLEAN",
                "dataSourceType": null,
                "dataTypeExt": "common",
                "defauleValue": "false",
                "direction": "IN",
                "example": null,
                "need": null,
                "xattrs": null
            },
            {
                "index": 10,
                "name": "dynPrjRad",
                "briefDescp": null,
                "descp": null,
                "dataType": "FLOAT",
                "dataSourceType": null,
                "dataTypeExt": "common",
                "defauleValue": "0",
                "direction": "IN",
                "example": null,
                "need": null,
                "xattrs": null
            },
            {
                "index": 11,
                "name": "isDissolve",
                "briefDescp": null,
                "descp": null,
                "dataType": "BOOLEAN",
                "dataSourceType": null,
                "dataTypeExt": "common",
                "defauleValue": "true",
                "direction": "IN",
                "example": null,
                "need": null,
                "xattrs": null
            },
            {
                "index": 12,
                "name": "color",
                "briefDescp": null,
                "descp": null,
                "dataType": "INT",
                "dataSourceType": null,
                "dataTypeExt": "common",
                "defauleValue": "1",
                "direction": "IN",
                "example": null,
                "need": null,
                "xattrs": null
            },
            {
                "index": 13,
                "name": "isMultiFeatureOpr",
                "briefDescp": null,
                "descp": null,
                "dataType": "BOOLEAN",
                "dataSourceType": null,
                "dataTypeExt": "common",
                "defauleValue": "false",
                "direction": "IN",
                "example": null,
                "need": null,
                "xattrs": null
            },
            {
                "index": 14,
                "name": "resultName",
                "briefDescp": null,
                "descp": null,
                "dataType": "STRING",
                "dataSourceType": null,
                "dataTypeExt": "common",
                "defauleValue": "",
                "direction": "OUT",
                "example": null,
                "need": null,
                "xattrs": null
            }
        ]
    }
}