let editList = {
  label: [{
    type: "MapgisUiInput",
    title: "标题",
    key: "title",
    value: "无标题",
  }, {
    type: "MapgisUiInput",
    title: "文本",
    key: "text",
    value: "无标题",
  }, {
    type: "MapgisUiSelect",
    title: "字体",
    key: "fontFamily",
    value: "sans-serif",
    dataSource: [{
      key: "微软雅黑",
      value: "微软雅黑"
    }, {
      key: "宋体",
      value: "宋体"
    }],
  }, {
    type: "MapgisUiInputNumber",
    title: "字体大小",
    key: "fontSize",
    value: 30,
  }, {
    type: "MapgisUiColorPicker",
    title: "字体颜色",
    key: "fontColor",
    value: "#000000",
  }, {
    type: "MapgisUiSlider",
    title: "透明度",
    key: "opacity",
    value: 100,
  }, {
    type: "MapgisUiInputNumber",
    title: "边线宽度",
    key: "outlineWidth",
    value: 1,
  }, {
    type: "MapgisUiColorPicker",
    title: "边线颜色",
    value: "#000000",
    key: "outlineColor",
  }, {
    type: "MapgisUiSlider",
    title: "边线透明度",
    key: "outlineOpacity",
    value: 100,
  }, {
    type: "MapgisUiColorPicker",
    title: "背景颜色",
    value: "#FFFFFF",
    key: "backgroundColor",
  }],
  point: [{
    type: "MapgisUiInput",
    title: "标题",
  }, {
    type: "MapgisUiInputNumber",
    title: "半径",
  }, {
    type: "MapgisUiColorPicker",
    title: "填充颜色",
  }, {
    type: "MapgisUiSlider",
    title: "透明度",
  }, {
    type: "MapgisUiInput",
    title: "边线",
  }, {
    type: "MapgisUiInputNumber",
    title: "边线宽度",
  }, {
    type: "MapgisUiColorPicker",
    title: "边线颜色",
  }, {
    type: "MapgisUiSlider",
    title: "边线透明度",
  }],
  line: [{
    type: "MapgisUiInput",
    title: "标题",
  }, {
    type: "MapgisUiInputNumber",
    title: "线宽",
  }, {
    type: "MapgisUiColorPicker",
    title: "颜色",
  }, {
    type: "MapgisUiSlider",
    title: "透明度",
  }, {
    type: "MapgisUiColorPicker",
    title: "背景颜色",
  }, {
    type: "MapgisUiSelect",
    title: "类型",
    dataSource: [{
      key: "实线",
      value: "实线"
    }, {
      key: "虚线",
      value: "虚线"
    }, {
      key: "箭头",
      value: "箭头"
    }],
  }],
  curve: [{
    type: "MapgisUiInput",
    title: "标题",
  }, {
    type: "MapgisUiInputNumber",
    title: "线宽",
  }, {
    type: "MapgisUiColorPicker",
    title: "颜色",
  }, {
    type: "MapgisUiSlider",
    title: "透明度",
  }, {
    type: "MapgisUiColorPicker",
    title: "背景颜色",
  }, {
    type: "MapgisUiSelect",
    title: "类型",
    dataSource: [{
      key: "实线",
      value: "实线"
    }, {
      key: "虚线",
      value: "虚线"
    }, {
      key: "箭头",
      value: "箭头"
    }],
  }],
  polygon: [{
    type: "MapgisUiInput",
    title: "标题",
  }, {
    type: "MapgisUiSelect",
    title: "填充类型",
    dataSource: [{
      key: "纯色",
      value: "纯色"
    }, {
      key: "网格",
      value: "网格"
    }, {
      key: "条纹",
      value: "条纹"
    }, {
      key: "图片",
      value: "图片"
    }],
  }, {
    type: "MapgisUiColorPicker",
    title: "填充颜色",
  }, {
    type: "MapgisUiSlider",
    title: "填充透明度",
  }, {
    type: "MapgisUiInputNumber",
    title: "边线宽度",
  }, {
    type: "MapgisUiColorPicker",
    title: "边线颜色",
  }, {
    type: "MapgisUiSlider",
    title: "边线透明度",
  }],
  rectangle: [{
    type: "MapgisUiInput",
    title: "标题",
  }, {
    type: "MapgisUiSelect",
    title: "填充类型",
    dataSource: [{
      key: "纯色",
      value: "纯色"
    }, {
      key: "网格",
      value: "网格"
    }, {
      key: "条纹",
      value: "条纹"
    }, {
      key: "图片",
      value: "图片"
    }],
  }, {
    type: "MapgisUiColorPicker",
    title: "填充颜色",
  }, {
    type: "MapgisUiSlider",
    title: "填充透明度",
  }, {
    type: "MapgisUiInputNumber",
    title: "边线宽度",
  }, {
    type: "MapgisUiColorPicker",
    title: "边线颜色",
  }, {
    type: "MapgisUiSlider",
    title: "边线透明度",
  }],
  circle: [{
    type: "MapgisUiInput",
    title: "标题",
  }, {
    type: "MapgisUiInputNumber",
    title: "半径",
  }, {
    type: "MapgisUiSelect",
    title: "填充类型",
    dataSource: [{
      key: "纯色",
      value: "纯色"
    }, {
      key: "网格",
      value: "网格"
    }, {
      key: "条纹",
      value: "条纹"
    }, {
      key: "图片",
      value: "图片"
    }],
  }, {
    type: "MapgisUiColorPicker",
    title: "填充颜色",
  }, {
    type: "MapgisUiSlider",
    title: "填充透明度",
  }, {
    type: "MapgisUiInputNumber",
    title: "边线宽度",
  }, {
    type: "MapgisUiColorPicker",
    title: "边线颜色",
  }, {
    type: "MapgisUiSlider",
    title: "边线透明度",
  }],
  cube: [{
    type: "MapgisUiInput",
    title: "标题",
  }, {
    type: "MapgisUiInputNumber",
    title: "长度",
  }, {
    type: "MapgisUiSelect",
    title: "填充类型",
    dataSource: [{
      key: "纯色",
      value: "纯色"
    }, {
      key: "网格",
      value: "网格"
    }, {
      key: "条纹",
      value: "条纹"
    }, {
      key: "图片",
      value: "图片"
    }],
  }, {
    type: "MapgisUiColorPicker",
    title: "填充颜色",
  }, {
    type: "MapgisUiSlider",
    title: "填充透明度",
  }],
  box: [{
    type: "MapgisUiInput",
    title: "标题",
    key: "title",
    value: "盒子模型",
  }, {
    type: "MapgisUiInputNumber",
    title: "高度",
    key: "extrudedHeight",
    value: 10000,
  }, {
    type: "MapgisUiColorPicker",
    title: "填充颜色",
    key: "color",
    value: "#FF0000",
  }, {
    type: "MapgisUiSlider",
    title: "填充透明度",
    key: "opacity",
    value: 100,
  }],
  polygonCube: [{
    type: "MapgisUiInput",
    title: "标题",
  }, {
    type: "MapgisUiInputNumber",
    title: "高度",
  }, {
    type: "MapgisUiSelect",
    title: "填充类型",
    dataSource: [{
      key: "纯色",
      value: "纯色"
    }, {
      key: "网格",
      value: "网格"
    }, {
      key: "条纹",
      value: "条纹"
    }, {
      key: "图片",
      value: "图片"
    }],
  }, {
    type: "MapgisUiColorPicker",
    title: "填充颜色",
  }, {
    type: "MapgisUiSlider",
    title: "填充透明度",
  }],
  cylinder: [{
    type: "MapgisUiInput",
    title: "标题",
  }, {
    type: "MapgisUiInputNumber",
    title: "半径",
  }, {
    type: "MapgisUiInputNumber",
    title: "高度",
  }, {
    type: "MapgisUiSelect",
    title: "填充类型",
    dataSource: [{
      key: "纯色",
      value: "纯色"
    }, {
      key: "网格",
      value: "网格"
    }, {
      key: "条纹",
      value: "条纹"
    }, {
      key: "图片",
      value: "图片"
    }],
  }, {
    type: "MapgisUiColorPicker",
    title: "填充颜色",
  }, {
    type: "MapgisUiSlider",
    title: "填充透明度",
  }],
  cone: [{
    type: "MapgisUiInput",
    title: "标题",
  }, {
    type: "MapgisUiInputNumber",
    title: "顶部半径",
  }, {
    type: "MapgisUiInputNumber",
    title: "高度",
  }, {
    type: "MapgisUiSelect",
    title: "填充类型",
    dataSource: [{
      key: "纯色",
      value: "纯色"
    }, {
      key: "网格",
      value: "网格"
    }, {
      key: "条纹",
      value: "条纹"
    }, {
      key: "图片",
      value: "图片"
    }],
  }, {
    type: "MapgisUiColorPicker",
    title: "填充颜色",
  }, {
    type: "MapgisUiSlider",
    title: "填充透明度",
  }],
  ellipsoid: [{
    type: "MapgisUiInput",
    title: "标题",
  }, {
    type: "MapgisUiInputNumber",
    title: "顶部半径",
  }, {
    type: "MapgisUiInputNumber",
    title: "高度",
  }, {
    type: "MapgisUiSelect",
    title: "填充类型",
    dataSource: [{
      key: "纯色",
      value: "纯色"
    }, {
      key: "网格",
      value: "网格"
    }, {
      key: "条纹",
      value: "条纹"
    }, {
      key: "图片",
      value: "图片"
    }],
  }, {
    type: "MapgisUiColorPicker",
    title: "填充颜色",
  }, {
    type: "MapgisUiSlider",
    title: "填充透明度",
  }],
  model: [{
    type: "MapgisUiInput",
    title: "标题",
  }, {
    type: "MapgisUiInput",
    title: "URL",
  }, {
    type: "MapgisUiInputNumber",
    title: "比例尺",
  }]
};

export default editList;